export enum MainActionsTypes {
  SET_ASSETS_LIST = '@@MAIN/SET_ASSETS_LIST',

  LOAD_PARAMS = '@@MAIN/LOAD_PARAMS',
  LOAD_PARAMS_SUCCESS = '@@MAIN/LOAD_PARAMS_SUCCESS',
  LOAD_PARAMS_FAILURE = '@@MAIN/LOAD_PARAMS_FAILURE',
}
