export const ROUTES = {
  NAV: {
    DEX: '/dex',
    LIQUIDITY: '/dex/liquidity',
    ASSETS: '/assets',
    EXPLORER: '/explorer',
    EXPLORER_CHARTS: '/explorer/charts',
    EXPLORER_BEAM: '/explorer/beam',
    EXPLORER_BANS: '/explorer/bans',
    EXPLORER_COUNTDOWN: '/explorer/countdown',
    EXPLORER_SUPPLY: '/explorer/supply',
    EXPLORER_BRIDGE: '/explorer/bridge',
    EXPLORER_MINING: '/explorer/mining',
    EXPLORER_ORACLE: '/explorer/oracle',
    EXPLORER_DAO: '/explorer/dao',
    EXPLORER_DAO_TREASURY: '/explorer/dao/treasury',
    EXPLORER_DAO_REVENUE: '/explorer/dao/revenue',
    EXPLORER_DAO_GOVERNANCE: '/explorer/dao/governance',
    DAO_PROPOSAL: '/explorer/dao/governance/proposal/:id',
    ASSET_INFO: '/asset/:id',
    PAIR_DETAIL: '/pair/:id',
    ATOMIC_SWAPS: '/atomic-swaps',
    ASSET_SWAPS: '/asset-swaps',
    DAPPS: '/dapps',
    PRIVACY: '/privacy',
    // explorer.beam.mw path shapes the BEAM desktop wallet links to.
    LEGACY_BLOCK: '/block',
    LEGACY_BLOCK_HASH: '/block/:hash',
    LEGACY_CONTRACT: '/contract/:cid',
    LEGACY_ASSET_DETAILS: '/assets/details/:id',
  },
};
